export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const GET_LEASE_TERMS = 'GET_LEASE_TERMS';
export const LEASE_TERMS_LOADING = 'LEASE_TERMS_LOADING';